[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "test"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"

[pypi-dependencies]
example = { path = ".", editable = true }

[feature.doc.dependencies]
sphinx = ">=9.1.0,<10"
jupyterlite-sphinx = ">=0.20,<0.22"
sphinx-autobuild = ">=2025.8.25,<2026"
jupyterlite-xeus = ">=4"

[feature.doc.tasks]
build-docs = { cmd = "python -m sphinx -b html -j auto . _build/html", depends-on = ["build"], cwd = "doc" }
autobuild-docs = { cmd = "sphinx-autobuild -b html -j auto . _build/html", depends-on = ["build"], cwd = "doc" }
build-docs-rtd = { cmd = "python -m sphinx -b html -j auto . _build/html", cwd = "doc" }

[feature.build.dependencies]
rattler-build = ">=0.57.2,<0.58"
python-build = ">=1.4.0,<2"

[feature.build.tasks]
build = { cmd = "rm -rf local-channel; rattler-build build -c conda-forge --output-dir local-channel --recipe ci/recipe/recipe.yaml", cwd = "." }

[environments]
doc = ["doc"]
build = { features = ["build"], no-default-feature = true }
