[project]
name = "example"
requires-python = ">=3.13"
license = "Apache-2.0"
version = "0.1"
dependencies = ["numpy"]

[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=80", "setuptools-scm>=8.1"]

[tool.setuptools_scm]
fallback_version = "9999"

[tool.setuptools.packages.find]
include = ["example*"]
